#!/bin/bash
#
# Copyright (c) 2010-2011 Nagios Enterprises, LLC.
# 
# NRDS Client Install Script
###########################

nagiosuser='nagios'
nagiosgroup='nagios'

groupaddbin='/usr/sbin/groupadd'
useraddbin='/usr/sbin/useradd'
usermodbin='/usr/sbin/usermod'

eval "$useraddbin" -n "$nagiosuser"
eval "$groupaddbin" "$nagiosgroup"
eval "$usermodbin" -a -G "$nagiosgroup" "$nagiosuser"


mkdir -p /usr/local/nrdp/clients
cp -r clients/* /usr/local/nrdp/clients
chown -R nagios:nagios /usr/local/nrdp/clients
chmod -R ug+xw /usr/local/nrdp/clients