#!/bin/bash
#
# Copyright (c) 2010-2011 Nagios Enterprises, LLC.
# 
# NRDS Client Install Script
###########################

PROGNAME=$(basename $0)

print_usage() {
    echo ""
    echo "$PROGNAME - NRDS Installation Script"
    echo ""
    echo "Usage: $PROGNAME <HOSTNAME> <INTERVAL>"
    echo ""
    echo "HOSTNAME - The name sent to the Nagios server to identify this host (no spaces)"
    echo "INTERVAL - Frequency in minutes the checks should run 1-59"
}
if [ "x$3" != "x" ];then
    echo "ERROR: Only expected 2 arguments."
    print_usage
    exit 1
fi
if [ "x$1" == "x" ] || [ "x$2" == "x" ];then
    print_usage
    exit 1
fi
cronhost="$1"
croninterval="$2"
nagiosuser='nagios'
nagiosgroup='nagios'
groupaddbin='/usr/sbin/groupadd'
useraddbin='/usr/sbin/useradd'
usermodbin='/usr/sbin/usermod'
installdir='/usr/local/nrdp/clients'

echo "Adding nagios user and group"
echo ""
eval "$useraddbin" -n "$nagiosuser"
eval "$groupaddbin" "$nagiosgroup"
eval "$usermodbin" -a -G "$nagiosgroup" "$nagiosuser"

echo "Installing NRDS Client"
echo ""
mkdir -p "$installdir"
cp -fr * "$installdir"
chown -R nagios:nagios "$installdir"
chmod -R ug+xw "$installdir"

echo "Adding cron jobs for $cronhost at a $croninterval minute interval"
echo ""
oldcron=$(sed "/-H $cronhost/d" /var/spool/cron/$nagiosuser)
echo "$oldcron" >/var/spool/cron/$nagiosuser
echo "*/$croninterval * * * * $installdir/nrds/nrds.sh -H $cronhost 2>&1" >> /var/spool/cron/$nagiosuser
echo "Updating config and plugins"
update="`$installdir/nrds/nrds_updater.sh -f`"
ret=$?
echo "Installation complete"
exit $ret
